eno=int(input("Enter employee number:"))
ename=input("Enter employee name:")
esal=int(input("Enter employee salary:"))
eadd=input("Enter employee address:")
emar=bool(input("Enter employee mariatal status:[True|False]"))
print("Please check the information")
print("Employee no:",eno)
print("Employee name:",ename)
print("Employee salary:",esal)
print("Employee address:",eadd)
print("Employee mariatal status:",emar)