a=int(input("Enter 1st number:"))
b=int(input("Enter 2nd number:"))
print("\nAddition")
print("Sum of 2 numbers is",a+b)
print("\nSubtraction")
print("Difference of 2 numbers is",a-b)
print("\nMultiplication")
print("Product of 2 numbers is",a*b)
print("\nDivision")
print("Division of 2 numbers is",a/b)
